name: CI-CD
on:
  push:
    branches: ["main"]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto' 
          java-version: '17'
      
      - name: Build project
        run: mvn clean install -DskipTests

      # - name: Upload JAR as artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: artedesejo-jar
      #     path: target/artedesejo-0.0.1-SNAPSHOT.jar

  release:
    name: Creation of Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      # - name: Download JAR artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: artedesejo-jar
      #     path: .

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.3.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            esperanca98/artedesejo:${{ github.run_number }}
            esperanca98/artedesejo:latest

      # - name: Build docker image
      #   run: docker build -t esperanca98/artedesejo .

      # - name: Push docker image
      #   run: docker push esperanca98/artedesejo    
